apiVersion: v1
kind: Service
metadata:
  name: grpcservice
spec:
  selector:
    app: grpcservice
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcservice
  template:
    metadata:
      labels:
        app: grpcservice
    spec:
      containers:
      - name: grpcservice
        image: {acr-prefix}.azurecr.io/grpcservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
